// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnfkjkmphxiqwqcbndin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZmtqa21waHhpcXdxY2JuZGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDQwNDAsImV4cCI6MjA2NzU4MDA0MH0.HlZT4J6KObt37J4LFbqMrb9ER705RYIRBXGS_2MTY2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});